---
# tasks file for solr

- name: install lsof (needed by solr start)
  yum: name=lsof state=present

- name: stat the solr tarball
  stat: path="/tmp/solr-{{solr_version}}.tgz"
  register: solr_tarball

- name: download Solr 
  get_url:
    url: http://archive.apache.org/dist/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz
    dest: /tmp
    sha256sum: '{{solr_tarball_sha256}}'
  when: solr_tarball.stat.exists == False

- name: ensure solr_home exists
  file: state=directory path={{solr_home}} owner=root group=root 

- name: untar Solr
  command: tar -C {{solr_home}} -xf solr-{{solr_version}}.tgz
  args:
    chdir: /tmp
    creates: '{{solr_home}}/solr-{{solr_version}}'

- name: set ownership to mapr for solr
  file: state=directory mode=0755 owner=mapr group=mapr recurse=true path={{item}}
  with_items:
    - '{{solr_home}}/solr-{{solr_version}}'

- name: create a volume for Solr
  mapr_volume: state=present name=solr.{{ansible_hostname}} path=/apps/solr/{{ansible_hostname}} createparent=1 replication=1 minreplication=1 mapr_webserver={{mapr_webserver}} username=mapr password=mapr

- name: copy solr config to solr's home
  sudo: yes
  sudo_user: mapr
  command: hadoop fs -cp -f -p file://{{solr_home}}/solr-{{solr_version}}/example hdfs:///apps/solr/{{ansible_hostname}}
  #command: cp -r {{solr_home}}/solr-{{solr_version}}/example /apps/solr/{{ansible_hostname}}

- name: disable locks on the index files (we are storing on NFS, no locking)
  sudo: yes
  lineinfile:
    line: "<lockType>${solr.lock.type:single}</lockType>"
    regexp: "<lockType>.*solr.lock.type"
    dest: '{{solr_home}}/solr-{{solr_version}}/example/solr/collection1/conf/solrconfig.xml'

- name: set data dir to a MapR FS directory
  sudo: yes
  lineinfile:
    line: "<dataDir>${solr.data.dir:/mapr/{{cluster_name}}/apps/solr/{{ansible_hostname}}}</dataDir>"
    regexp: "<dataDir>.*solr.data.dir"
    dest: '{{solr_home}}/solr-{{solr_version}}/example/solr/collection1/conf/solrconfig.xml'

- name: write warden.conf for solr
  sudo: yes
  template: src=warden.solr.conf.j2 dest=/opt/mapr/conf/conf.d/warden.solr.conf mode=0644 owner=mapr group=mapr 
